# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from conftest import USER, PASSWORD
from pages.login_page import LoginPage

def test_loginKO(driver):
  driver.get("https://the-internet.herokuapp.com/login")
  login_page = LoginPage(driver)

  login_page.login("user", "password")

  assert "Your username is invalid!" in login_page.get_login_message()

def test_login(driver):
  driver.get("https://the-internet.herokuapp.com/login")
  login_page = LoginPage(driver)
  login_page.login("tomsmith", "SuperSecretPassword!")

  assert "You logged into a secure area!" in login_page.get_login_message()

